import Head from "next/head";
import Navbar from "./Navbar";
import Intro from "./Intro";
import MyStory from "./My-story";
import Projects from "./Projects";
import Contact from "./Contact";
import Footer from "./footer";
import { BrowserRouter, Link, Switch, Route } from "react-router-dom";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Matt Rao | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">

          <Navbar />
          <Intro />
          <MyStory />
          <Projects />
          <Contact />
          <Footer />
        
      </main>
    </div>
  );
}
